config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/signup', to: 'users#new'
    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    delete '/signout', to: 'sessions#destroy'
    resources :users

  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  include SessionsHelper

  private

    def set_locale
      I18n.locale = params[:locale] if params[:locale].present?
    end

    def default_url_options(options = {})
      {locale: I18n.locale}
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = t('.sign_in_failure')
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t('.sign_up_success')
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    if page_title.empty?
      t('.base_title')
    else
      page_title + " | " + t('.base_title')
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><%= t('.copyright') %></small>
  <nav>
    <ul>
      <li><%= link_to t('.home'), root_path %></li>
      <li><%= link_to t('.about'), about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('.applogo'), root_path, id: "logo" %>
    </div>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t('.home'), root_path %></li>
      <li><%= link_to t('.about'), about_path %></li>
      <% if logged_in? %>
      <li><%= link_to t('.users'), '#' %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('.account') %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t('.profile'), current_user %></li>
          <li><%= link_to t('.settings'), '#' %></li>
          <li class="divider"></li>
          <li><%= link_to t('.sign_out'), signout_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to t('.sign_in'), signin_path %></li>
      <% end %>
      <ul class="language navbar-right">
        <li><%= link_to "English", locale: "en" %></li>
        <li><%= link_to "Español", locale: "es" %></li>
      </ul>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container container-main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('errors.template.header', count: @user.errors.count) %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, t('.about_title')) %>

<p><%= t('.appinfo') %></p>

app/views/static_pages/home.html.erb
<% provide(:title, t('.home_title')) %>
<div class="center jumbotron">
  <h1><%= t('.appname') %> </h1>
  <h3><%= t('.welcome') %></h3>
</div>
<h1><%= t('.hello') %></h1>
<div class="text-center">
  <%= link_to t('.sign_up'), signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, t('.sign_up_title')) %>
<h1><%= t('.sign_up') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>
      <%= f.label t('.name') %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label t('.email') %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label t('.password') %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t('.confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t('.sign_up_button'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>